### PR TITLE
Apply PSR-2 to code samples

### PR DESCRIPTION
**Pull request by svenluijten**
This PR applies [PSR-2](http://www.php-fig.org/psr/psr-2/) to all the code samples in the README. If this repository is going to be a resource where people come for examples, we should adhere to a widely accepted coding standard in all code snippets.

### CODE REVIEW

**Comment by kamranahmedse** [comment]
Thanks @svenluijten but I think it is fine

**Comment by svenluijten** [comment]
Could you elaborate more about why you think it's fine the way it is now? The biggest frameworks out there adhere to PSR-2, is there any reason a big repository of examples shouldn't also accept it?

**Comment by kamranahmedse** [comment]
It is fine because I don't think it matters in this case. What matters is it should be consistent and it is.

**Comment by svenluijten** [comment]
I disagree, but it's your call 🙂

**Comment by luciano-jr** [comment]
@kamranahmedse I really think its matters, show the code in the mainly adopted standard in the community helps to make it more stronger, and as your purpose with this project, make the things more standardized across the whole projects.

**Comment by svenluijten** [comment]
This was just merged in #64 :-)

**Comment by luciano-jr** [comment]
Nice ;-)

**Pull request closed without merging**
